name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, "3.0", 3.1, 3.2, 3.3, head]
        gemfile: [rails_5_2, rails_6]
        exclude:
          - ruby: "3.0"
            gemfile: rails_5_2
          - ruby: 3.1
            gemfile: rails_5_2
          - ruby: 3.2
            gemfile: rails_5_2
          - ruby: 3.3
            gemfile: rails_5_2
          - ruby: head
            gemfile: rails_5_2
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
